### ISSUE TITLE
Panic from an utoipa-generated spec: "unexpected token"

### ISSUE THREAD

**Issue by antifuchs** [kurtbuilds/libninja#22]
I'm trying to use libninja to generate an OpenAPI client for my in-progress web api. The spec is here: https://gist.github.com/antifuchs/f7bdaabcf9ea432904be944fc4b09c02

When generating from latest git HEAD, I get the following output:

```console
:;    env RUST_BACKTRACE=full ~/.cargo/bin/libninja gen -l rust -o src/lz-openapi --repo antifuchs/lz lz-openapi ~mess/openapi.json
src/lz-openapi/Cargo.toml: Wrote file.
src/lz-openapi/src/model.rs: Wrote file.
src/lz-openapi/src/model/annotated_bookmark.rs: Wrote file.
src/lz-openapi/src/model/associated_link.rs: Wrote file.
src/lz-openapi/src/model/existing_bookmark.rs: Wrote file.
src/lz-openapi/src/model/existing_tag.rs: Wrote file.
src/lz-openapi/src/model/list_bookmarks_matching_response.rs: Wrote file.
src/lz-openapi/src/request/list_bookmarks_matching.rs: Wrote file.
src/lz-openapi/src/request.rs: Wrote file.
src/lz-openapi/src/lib.rs: Wrote file.
src/lz-openapi/src/serde.rs: Wrote file.
thread 'main' panicked at mir_rust/src/import.rs:21:54:
Failed to parse as syn::Path: lz-openapi::LzOpenapiClient: Error("unexpected token")
stack backtrace:
   0:        0x102b1342c - std::backtrace_rs::backtrace::libunwind::trace::hdc7d2d82dacc83e6
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/../../backtrace/src/backtrace/libunwind.rs:104:5
   1:        0x102b1342c - std::backtrace_rs::backtrace::trace_unsynchronized::h11fcbf27db856d40
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x102b1342c - std::sys_common::backtrace::_print_fmt::h117e5fb45bd92414
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:68:5
   3:        0x102b1342c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4e6df6dd376d525
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:44:22
   4:        0x102b32430 - core::fmt::rt::Argument::fmt::h4f724c1ed2e34985
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/fmt/rt.rs:142:9
   5:        0x102b32430 - core::fmt::write::h5a442bf928ef18fb
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/fmt/mod.rs:1120:17
   6:        0x102b10b74 - std::io::Write::write_fmt::h01fe6f9cc882fac7
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/io/mod.rs:1846:15
   7:        0x102b13260 - std::sys_common::backtrace::_print::h15d065176d59d5e1
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:47:5
   8:        0x102b13260 - std::sys_common::backtrace::print::h249c7fd853efd630
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:34:9
   9:        0x102b146a4 - std::panicking::default_hook::{{closure}}::h539bfee0454d0951
  10:        0x102b143ec - std::panicking::default_hook::he5a7d244fe90fc13
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:292:9
  11:        0x102b14ae0 - std::panicking::rust_panic_with_hook::h9b82bdc13ccb171b
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:781:13
  12:        0x102b149d4 - std::panicking::begin_panic_handler::{{closure}}::hf609a05c98725eb7
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:659:13
  13:        0x102b138b0 - std::sys_common::backtrace::__rust_end_short_backtrace::hea0399d584786a2b
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys_common/backtrace.rs:171:18
  14:        0x102b1475c - rust_begin_unwind
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
  15:        0x102b6478c - core::panicking::panic_fmt::hb4d79f470bcac176
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14
  16:        0x102b64b40 - core::result::unwrap_failed::h66d43c215ff45232
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/result.rs:1649:5
  17:        0x10273fdc8 - mir_rust::import::<impl mir_rust::ToRustCode for mir::import::Import>::to_rust_code::inner::h73d83d3fe4693b20
  18:        0x102751ec4 - mir_rust::import::<impl mir_rust::ToRustCode for mir::import::Import>::to_rust_code::hf0c7922db2316ce6
  19:        0x10275727c - mir_rust::file::<impl mir_rust::ToRustCode for mir::file::File<proc_macro2::TokenStream>>::to_rust_code::h207666d118ebd480
  20:        0x102587344 - libninja::rust::codegen::example::generate_example::haf780320270eec4c
  21:        0x102591328 - libninja::rust::write_examples::heae1dff2d4d5b608
  22:        0x10258e604 - libninja::rust::generate_rust_library::hc60db51a47a5c2e9
  23:        0x1025dd818 - libninja::command::generate::Generate::run::heb6d22d4e9424f5e
  24:        0x102458c60 - libninja::main::hd8279afa37ef2630
  25:        0x102456be8 - std::sys_common::backtrace::__rust_begin_short_backtrace::h51bd56bf77bdc108
  26:        0x10245aca8 - std::rt::lang_start::{{closure}}::h79c167ffea26575c
  27:        0x102b0985c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc7fa490c25ff5c7e
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:284:13
  28:        0x102b0985c - std::panicking::try::do_call::h357310772e5ed201
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:554:40
  29:        0x102b0985c - std::panicking::try::h7be07bf7667211c0
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:518:19
  30:        0x102b0985c - std::panic::catch_unwind::h3ab45e592d6c9793
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panic.rs:142:14
  31:        0x102b0985c - std::rt::lang_start_internal::{{closure}}::h522f1a8ded7e5ad3
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/rt.rs:148:48
  32:        0x102b0985c - std::panicking::try::do_call::h403386826d59f38d
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:554:40
  33:        0x102b0985c - std::panicking::try::h5e255b7a06373cce
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:518:19
  34:        0x102b0985c - std::panic::catch_unwind::h462489ab339aac24
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panic.rs:142:14
  35:        0x102b0985c - std::rt::lang_start_internal::h7f00bef3cf1b3caa
                               at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/rt.rs:148:20
  36:        0x102459b78 - _main
```

**Comment by kurtbuilds** [comment]
Great. I'll close this for now. Feel free to re-open if anything changes.
